apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bank-app-deployment.yaml
  - bank-app-service.yaml
  - h2data-pvc.yaml
  - bank-app-ingress.yaml
  - bank-app-configmap.yaml

labels:
  - pairs:
      app: bank-app
      environment: production 