apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bank-app
  name: bank-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bank-app-role-binding
  namespace: bank-app
subjects:
- kind: ServiceAccount
  name: bank-app-sa
  namespace: bank-app
roleRef:
  kind: Role
  name: bank-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bank-app-sa
  namespace: bank-app 