apiVersion: v1
kind: Secret
metadata:
  name: bank-app-secrets
  namespace: bank-app
type: Opaque
data:
  # Les valeurs doivent être encodées en base64
  # Exemple: echo -n "votre-valeur" | base64
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # 'password123' en base64
  API_KEY: YXBpLWtleS0xMjM=      # 'api-key-123' en base64 