server:
  port: 8989

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:./data/h2/mydb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: bankapp
    password: changeit
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    basic:
      enabled: false

